version: "3"
services:
  web:
    container_name: cont_web
    restart: always
    build:
      dockerfile: Dockerfile.web
      context: ./
    expose:
      - "3000"
    ports :
    - "3000:3000"
  judge:
    container_name: cont_judge
    build:
      dockerfile: Dockerfile.judge
      context: ./judge/
    expose:
      - "8080"
    ports:
      - "8080:8080"
  
  